/*
 * Gambio GX3 API
 *
 * This is the Gambio GX Restful API documentation for the GX shop software. You can find out more about Gambio at [http://www.gambio.de](http://www.gambio.de).
 *
 * API version: 3.9.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package client

type ProductsDeleteSuccessResponse struct {
	Code int64 `json:"code"`
	Status string `json:"status"`
	Action string `json:"action"`
	Resource string `json:"resource"`
	ProductId int64 `json:"productId"`
}
