/*
 * Gambio GX3 API
 *
 * This is the Gambio GX Restful API documentation for the GX shop software. You can find out more about Gambio at [http://www.gambio.de](http://www.gambio.de).
 *
 * API version: 3.9.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package client

type DefaultSuccessResponseWithProductIdAndCategoryIDs struct {
	Code int64 `json:"code,omitempty"`
	Status string `json:"status,omitempty"`
	Action string `json:"action,omitempty"`
	Resource string `json:"resource,omitempty"`
	ProductId int64 `json:"productId,omitempty"`
	OldCategoryId int64 `json:"oldCategoryId,omitempty"`
	NewCategoryId int64 `json:"newCategoryId,omitempty"`
}
