/*
 * Gambio GX3 API
 *
 * This is the Gambio GX Restful API documentation for the GX shop software. You can find out more about Gambio at [http://www.gambio.de](http://www.gambio.de).
 *
 * API version: 3.9.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package client

type GxCustomerEmail struct {
	Id           int64                   `json:"id,omitempty"`
	Subject      string                  `json:"subject"`
	Sender       *GxCustomerEmailAddress `json:"sender"`
	Recipient    *GxCustomerEmailAddress `json:"recipient"`
	ContentHtml  string                  `json:"contentHtml"`
	IsPending    bool                    `json:"isPending"`
	CreationDate string                  `json:"creationDate"`
	SentDate     string                  `json:"sentDate"`
	Bcc          []string                `json:"bcc"`
	Cc           []string                `json:"cc"`
	Attachments  []string                `json:"attachments"`
}
