/*
 * Gambio GX3 API
 *
 * This is the Gambio GX Restful API documentation for the GX shop software. You can find out more about Gambio at [http://www.gambio.de](http://www.gambio.de).
 *
 * API version: 3.9.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package client

type GxProductListing struct {
	Id int64 `json:"id"`
	IsActive bool `json:"isActive"`
	SortOrder int64 `json:"sortOrder"`
	DateAdded string `json:"dateAdded"`
	DateAvailable string `json:"dateAvailable"`
	LastModified string `json:"lastModified"`
	OrderedCount int64 `json:"orderedCount"`
	ProductModel string `json:"productModel"`
	Ean string `json:"ean"`
	Price float32 `json:"price"`
	DiscountAllowed int64 `json:"discountAllowed"`
	TaxClassId int64 `json:"taxClassId"`
	Quantity float32 `json:"quantity"`
	Name string `json:"name"`
	Image string `json:"image"`
	ImageAltText string `json:"imageAltText"`
	UrlKeywords string `json:"urlKeywords"`
	Weight float32 `json:"weight"`
	ShippingCosts float32 `json:"shippingCosts"`
	ShippingTimeId int64 `json:"shippingTimeId"`
	ProductTypeId int64 `json:"productTypeId"`
	ManufacturerId int64 `json:"manufacturerId"`
	QuantityUnitId int64 `json:"quantityUnitId"`
	IsFsk18 bool `json:"isFsk18"`
	IsVpeActive bool `json:"isVpeActive"`
	VpeId int64 `json:"vpeId"`
	VpeValue float32 `json:"vpeValue"`
	SpecialOfferId int64 `json:"specialOfferId"`
}
