/*
 * Gambio GX3 API
 *
 * This is the Gambio GX Restful API documentation for the GX shop software. You can find out more about Gambio at [http://www.gambio.de](http://www.gambio.de).
 *
 * API version: 3.9.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package client

type CategorySettings struct {
	CategoryListingTemplate          string                     `json:"categoryListingTemplate"`
	ProductListingTemplate           string                     `json:"productListingTemplate"`
	SortColumn                       string                     `json:"sortColumn"`
	SortDirection                    string                     `json:"sortDirection"`
	OnSitemap                        bool                       `json:"onSitemap"`
	SitemapPriority                  string                     `json:"sitemapPriority"`
	SitemapChangeFrequency           string                     `json:"sitemapChangeFrequency"`
	ShowAttributes                   bool                       `json:"showAttributes"`
	ShowGraduatedPrice               bool                       `json:"showGraduatedPrice"`
	ShowQuantity                     bool                       `json:"showQuantity"`
	ShowQuantityInfo                 bool                       `json:"showQuantityInfo"`
	ShowSubCategories                bool                       `json:"showSubCategories"`
	ShowSubCategoryImages            bool                       `json:"showSubCategoryImages"`
	ShowSubCategoryNames             bool                       `json:"showSubCategoryNames"`
	ShowSubCategoryProducts          bool                       `json:"showSubCategoryProducts"`
	ShowCategoriesImageInDescription bool                       `json:"showCategoriesImageInDescription,omitempty"`
	IsViewModeTiled                  bool                       `json:"isViewModeTiled"`
	ShowCategoryFilter               bool                       `json:"showCategoryFilter"`
	FilterSelectionMode              int64                      `json:"filterSelectionMode"`
	FilterValueDeactivation          int64                      `json:"filterValueDeactivation"`
	GroupPermissions                 []CategoryGroupPermissions `json:"groupPermissions"`
}
