/*
 * Gambio GX3 API
 *
 * This is the Gambio GX Restful API documentation for the GX shop software. You can find out more about Gambio at [http://www.gambio.de](http://www.gambio.de).
 *
 * API version: 3.9.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package gambio

type GxCustomerGroupConfigurations struct {
	MinOrder int64 `json:"minOrder"`
	MaxOrder int64 `json:"maxOrder"`
	Discount int64 `json:"discount"`
	OtDiscount int64 `json:"otDiscount"`
	UnallowedPaymentModules []string `json:"unallowedPaymentModules"`
	UnallowedShippingModules []string `json:"unallowedShippingModules"`
}
