/*
 * Gambio GX3 API
 *
 * This is the Gambio GX Restful API documentation for the GX shop software. You can find out more about Gambio at [http://www.gambio.de](http://www.gambio.de).
 *
 * API version: 3.9.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package gambio

type GxOrderAddress struct {
	Gender string `json:"gender"`
	Firstname string `json:"firstname"`
	Lastname string `json:"lastname"`
	Company string `json:"company"`
	Street string `json:"street"`
	HouseNumber string `json:"houseNumber"`
	AdditionalAddressInfo string `json:"additionalAddressInfo"`
	Suburb string `json:"suburb"`
	Postcode string `json:"postcode"`
	City string `json:"city"`
	CountryId int64 `json:"countryId"`
	ZoneId int64 `json:"zoneId"`
	B2bStatus bool `json:"b2bStatus"`
}
