/*
 * Gambio GX3 API
 *
 * This is the Gambio GX Restful API documentation for the GX shop software. You can find out more about Gambio at [http://www.gambio.de](http://www.gambio.de).
 *
 * API version: 3.9.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package gambio

type GxProductImage struct {
	Filename string `json:"filename"`
	IsPrimary bool `json:"isPrimary"`
	IsVisible bool `json:"isVisible"`
	ImageAltText *GxMultiLangOption `json:"imageAltText"`
}
