/*
 * Gambio GX3 API
 *
 * This is the Gambio GX Restful API documentation for the GX shop software. You can find out more about Gambio at [http://www.gambio.de](http://www.gambio.de).
 *
 * API version: 3.9.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package gambio

type GxOrderItem struct {
	Id int64 `json:"id,omitempty"`
	Model string `json:"model"`
	Name string `json:"name"`
	Quantity int64 `json:"quantity"`
	Price int64 `json:"price"`
	FinalPrice int64 `json:"finalPrice"`
	Tax int64 `json:"tax"`
	IsTaxAllowed bool `json:"isTaxAllowed"`
	Discount int64 `json:"discount"`
	ShippingTimeInformation string `json:"shippingTimeInformation"`
	CheckoutInformation string `json:"checkoutInformation"`
	Attributes *GxOrderItemAttributes `json:"attributes"`
	DownloadInformation []string `json:"downloadInformation"`
	AddonValues *GxOrderItemAddons `json:"addonValues"`
	QuantityUnitName string `json:"quantityUnitName"`
	GxCustomizerData []string `json:"gxCustomizerData"`
}
