/*
 * Gambio GX3 API
 *
 * This is the Gambio GX Restful API documentation for the GX shop software. You can find out more about Gambio at [http://www.gambio.de](http://www.gambio.de).
 *
 * API version: 3.9.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package client

type GxOrderItemAttributes struct {
	Id int64 `json:"id,omitempty"`
	Name string `json:"name"`
	Value string `json:"value"`
	Price int64 `json:"price"`
	PriceType string `json:"priceType"`
	CombisId int64 `json:"combisId"`
	OptionId int64 `json:"optionId"`
	OptionValueId int64 `json:"optionValueId"`
}
