/*
 * Gambio GX3 API
 *
 * This is the Gambio GX Restful API documentation for the GX shop software. You can find out more about Gambio at [http://www.gambio.de](http://www.gambio.de).
 *
 * API version: 3.9.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package gambio

type GxOrderAddonValues struct {
	CcCvv string `json:"ccCvv"`
	CcExpires string `json:"ccExpires"`
	CcIssue string `json:"ccIssue"`
	CcNumber string `json:"ccNumber"`
	CcOwner string `json:"ccOwner"`
	CcStart string `json:"ccStart"`
	CcType string `json:"ccType"`
	CustomerIp string `json:"customerIp"`
	DownloadAbandonmentStatus string `json:"downloadAbandonmentStatus"`
	ServiceAbandonmentStatus string `json:"serviceAbandonmentStatus"`
}
