/*
 * Gambio GX3 API
 *
 * This is the Gambio GX Restful API documentation for the GX shop software. You can find out more about Gambio at [http://www.gambio.de](http://www.gambio.de).
 *
 * API version: 3.9.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package gambio

type GxOrderTotal struct {
	Id int64 `json:"id,omitempty"`
	Title string `json:"title"`
	Value int64 `json:"value"`
	ValueText string `json:"valueText"`
	Class string `json:"class"`
	SortOrder int64 `json:"sortOrder"`
}
