/*
 * Gambio GX3 API
 *
 * This is the Gambio GX Restful API documentation for the GX shop software. You can find out more about Gambio at [http://www.gambio.de](http://www.gambio.de).
 *
 * API version: 3.9.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package gambio

type GxTrackingCode struct {
	Id string `json:"id"`
	// A tracking code is bound to an order on creation.
	OrderId string `json:"orderId"`
	TrackingCode string `json:"trackingCode"`
	ParcelServiceId string `json:"parcelServiceId"`
	ParcelServiceName string `json:"parcelServiceName,omitempty"`
	LanguageId string `json:"languageId"`
	Url string `json:"url,omitempty"`
	Comment string `json:"comment,omitempty"`
	CreationDate string `json:"creationDate"`
}
